### ISSUE TITLE
Round card edge

### ISSUE THREAD

**Issue by JamesNZL** [pumbas600/github-contributions#25]
### Related Problem

![image](https://github.com/pumbas600/github-contributions/assets/44986932/1a1cd416-7e91-4a5e-b89c-7a289a6b2ac5)

Card corners aren't rounded (or are only barely).

### Requested Feature

Round the corners, to match the de-facto standard that a lot of the other README cards seem to have.

Not sure what the exact measurement they're using is sorry, and too tired to look through the source 😅

**Comment by pumbas600** [comment]
Yeah, it's probably a good idea for the consistency :)

Do you think there should be an option to disable it?

**Comment by pumbas600** [comment]
Ah, that's definitely a better idea
